-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Drink CASCADE;
DROP TABLE IF EXISTS Drinker CASCADE;
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS Favourite CASCADE;
DROP TABLE IF EXISTS DrinkIngredient CASCADE;
